In [2]:
import numpy as np

In [14]:
escalar = 5.679
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3,30], [4,5,6,31], [7,8,9,32]],
    [[11,12,13,33], [14,15,16,34], [17,18,19,35]],
    [[21,22,23,36], [24,25,26,37], [27,28,29,38]]
])

In [8]:
vector_t = vector.T
print(vector_t)

[3 4 5 6]


In [9]:
matriz_t = matriz.T
print(matriz_t)

[[1 3 5]
 [2 4 6]]


In [10]:
tensor_t = tensor.T
print(tensor_t)

[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]

 [[30 33 36]
  [31 34 37]
  [32 35 38]]]


In [12]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[32,21],[33,44],[15,69]])
C = A+B
C

array([[33, 23],
       [36, 48],
       [20, 75]])

In [16]:
D = matriz + escalar
D

array([[ 6.679,  7.679],
       [ 8.679,  9.679],
       [10.679, 11.679]])