In [8]:
import numpy as np

escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [9]:
A = matriz * vector # m x n * n = m x n
print(A)

[[ 2  6]
 [ 6 12]
 [10 18]]


In [10]:
B = matriz.dot(vector) # m x n dot n = m
print(B)

[ 8 18 28]


In [12]:
A = np.array([
[1,2,3],
[4,5,6],
[7,8,9],
[10,11,12]
])

B = np.array([
[2,3],
[5,7],
[11,13]
])


In [13]:
A.shape

(4, 3)

In [14]:
B.shape

(3, 2)

In [16]:
C = A.dot(B) # 4x3 dot 3x2 = 4x2 -> mxn dot nxl = mxl
C

array([[ 45,  56],
       [ 99, 125],
       [153, 194],
       [207, 263]])

In [17]:
D = B.dot(A)
D

ValueError: shapes (3,2) and (4,3) not aligned: 2 (dim 1) != 4 (dim 0)