In [1]:
import numpy as np
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

In [4]:
# propiedad asociativa

A_BC = np.dot(A,np.dot(B,C))
print(A_BC)
AB_C = np.dot(np.dot(A,B),C)
print(AB_C)
print(A_BC == AB_C)

[[ 60  26]
 [145  63]
 [295 129]]
[[ 60  26]
 [145  63]
 [295 129]]
[[ True  True]
 [ True  True]
 [ True  True]]


In [6]:
#propiedad distributiva
D = A.dot(B+C)
print(D)
E = A.dot(B) + A.dot(C)
print(E)
print(D==E)

[[ 26  17]
 [ 62  41]
 [122  83]]
[[ 26  17]
 [ 62  41]
 [122  83]]
[[ True  True]
 [ True  True]
 [ True  True]]


In [7]:
#propiedad conmutativa

F = B.dot(C)
print(F)
G = C.dot(B)
print(G)
print(F==G)

[[15  7]
 [10  4]]
[[ 5 10]
 [ 8 14]]
[[False False]
 [False False]]
