In [1]:
import numpy as np

In [3]:
identidad = np.eye(4)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
vector = np.array([[2],[3],[5],[7]])

In [5]:
print(identidad.dot(vector))

[[2.]
 [3.]
 [5.]
 [7.]]


In [7]:
A = np.array([[1,0,1],[0,1,1],[-1,1,1]])
print(A)

AInv = np.linalg.inv(A)
print(AInv)

A.dot(AInv)

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]
[[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])